language: cpp

compiler:
    - clang

before_install:
    - brew update
    - brew install cmake
    - brew install qt5

before_script:
    - /usr/local/bin/cmake . -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake

script:
    - make VERBOSE=1
    - make package

os:
    - osx
