sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qy update

install:
    - sudo apt-get -qy --only-upgrade install cmake
    - sudo apt-get -qy install qt56base qt56tools qt56translations
    - sudo apt-get -qy install gcc-5 g++-5

script:
    - export CXX=g++-5
    - export CC=gcc-5
    - cmake -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake .
    - make VERBOSE=1
    - make

os:
    - linux

